### PR TITLE
TF-M v2.0.0 upmerge 

### PR DESCRIPTION
**Pull request by mswarowsky**

### CODE REVIEW

**Review by d3zd3z — APPROVED** [review]

**Comment by carlescufi** [comment]
@SebastianBoe can you please take a look?

**Comment by SebastianBoe** [comment]
will do

**Comment by SebastianBoe** [comment]
I see we revert some commits before the merge, but we don't re-apply them.

May I ask why they are not reapplied?

**Comment by mswarowsky** [comment]
> I see we revert some commits before the merge, but we don't re-apply them.
> 
> May I ask why they are not reapplied?

I guess because they were cherry-picked before? but let me know which commits you mean.

**Review by SebastianBoe — APPROVED** [review]

**Pull request merged**
